name: Salesforce Deployments

on:
  push:
    branches: 
    - main

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Install salesforce cli
          run: |
            npm install sfdx-cli --global

        - name: Authenticate with Salesforce
          run: |
            echo ${{ secrets.SFDX_AUTH_URL }} > ./authfile.txt
            sfdx force:auth:sfdxurl:store -f ./authfile.txt --setalias target_poc -s

      #  - name: Validate and Deploy to org
      #   run: |
      #     sfdx force:source:deploy -c -p force-app -u target_poc
      #    sfdx force:source:deploy -p force-app -u target_poc

       # Install PMD
        - name: Install PMD
          run: |
            PMD_VERSION=`cat PMD/pmd-version.txt`
            wget https://github.com/PMD/PMD/releases/download/PMD_releases%2F$PMD_VERSION/PMD-bin-$PMD_VERSION.zip
            unzip PMD-bin-$PMD_VERSION.zip -d ~
            mv ~/PMD-bin-$PMD_VERSION ~/PMD
            ~/PMD/bin/run.sh PMD --version

        # Run PMD scan
        - name: 'Run PMD scan'
          run: ~/PMD/bin/run.sh PMD -d force-app -R PMD/ruleset.xml -f text

        - name: Install the sfdx-git-delta plugin
          run: |
            echo 'y' | sfdx plugins:install sfdx-git-delta
            
        - name: Generate the package.xml for delta files
          run: |
            mkdir delta
            sfdx sgd:source:delta HEAD^ HEAD --output . 
            echo "--- package.xml generated with added and modified metadata ---"
            cat delta/package/package.xml
            
        - name: Deploy Delta components to Salesforce
          run: |
            sf project deploy validate --manifest package/package.xml -l NoTestRun -u target_poc
# sfdx force:source:deploy -x delta/package/package.xml -c -l NoTestRun -u target_poc
            
