name: Salesforce Deployments

on:
  push:
    branches: 
    - main

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      
      # Checkout source code
        - name: Checkout source code
          uses: actions/checkout@v4
          with: 
            fetch-depth: 2  # Fetch the last 2 commits

      # This sets the fetch depth to 2, ensuring that the workflow fetches at least the last two commits.
      # This allows git diff HEAD~1 to work correctly by ensuring HEAD~1 is available.
      
      # Install salesforce cli
        - name: Install salesforce cli
          run: |
            npm install sfdx-cli --global

      # Authenticate with Salesforce
        - name: Authenticate with Salesforce
          run: |
            echo ${{ secrets.SFDX_AUTH_URL }} > ./authfile.txt
            sfdx force:auth:sfdxurl:store -f ./authfile.txt --setalias target_poc -s

       # Install PMD
        - name: Install PMD
          run: |
            PMD_VERSION=`cat pmd/pmd-version.txt`
                wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-bin-$PMD_VERSION.zip
                unzip pmd-bin-$PMD_VERSION.zip -d ~
                mv ~/pmd-bin-$PMD_VERSION ~/pmd
                ~/pmd/bin/run.sh pmd --version

      # Run PMD scan
        - name: 'Run PMD scan'
          run: ~/pmd/bin/run.sh pmd -d force-app -R pmd/ruleset.xml -f text

      # Install the sfdx-git-delta plugin     
        - name: Install the sfdx-git-delta plugin
          run: |
            echo 'y' | sfdx plugins:install sfdx-git-delta

      # Determine changed files  
      #  - name: Determine changed files
      #    run: |
      #      git fetch origin main
      #      git diff --name-only HEAD~1 > changed_files.txt
      #      echo "::set-output name=files::$(cat changed_files.txt | tr '\n' ' ')"

      # Generate the package.xml for delta files  
       # Generate the package.xml for delta files     
        - name: Generate the package.xml for delta files
          run: |
            mkdir -p delta
            sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output . --ignore-whitespace -d -i .sgdignore 
            echo "--- package.xml generated with added and modified metadata ---"
            cat delta/package/package.xml

      # Validate & Deploy Delta components to Salesforce    
        - name: Validate & Deploy Delta components to Salesforce
          run: |
          if [ -f delta/package/package.xml ]; 
          then
             sfdx force:source:deploy -x delta/package/package.xml --checkonly
             sfdx force:source:deploy -x delta/package/package.xml
          else
            echo "No changes to deploy."
          fi           
            
            
