name: Salesforce Deployments

on:
  push:
    branches: 
    - main

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      
      # Checkout source code
        - name: Checkout source code
          uses: actions/checkout@v4
          with: 
            fetch-depth: 2  # Fetch the last 2 commits

      # This sets the fetch depth to 2, ensuring that the workflow fetches at least the last two commits.
      # This allows git diff HEAD~1 to work correctly by ensuring HEAD~1 is available.
      
      # Install salesforce cli
        - name: Install salesforce cli
          run: |
            npm install sfdx-cli --global

      # Authenticate with Salesforce
        - name: Authenticate with Salesforce
          run: |
            echo ${{ secrets.SFDX_AUTH_URL }} > ./authfile.txt
            sfdx force:auth:sfdxurl:store -f ./authfile.txt --setalias target_poc -s

       # Install PMD
        - name: Install PMD
          run: |
            PMD_VERSION=`cat pmd/pmd-version.txt`
                wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-bin-$PMD_VERSION.zip
                unzip pmd-bin-$PMD_VERSION.zip -d ~
                mv ~/pmd-bin-$PMD_VERSION ~/pmd
                ~/pmd/bin/run.sh pmd --version

      # Run PMD scan
        - name: 'Run PMD scan'
          run: ~/pmd/bin/run.sh pmd -d force-app -R pmd/ruleset.xml -f text

      # Install the sfdx-git-delta plugin     
        - name: Install the sfdx-git-delta plugin
          run: |
            echo 'y' | sfdx plugins:install sfdx-git-delta

      # Generate the package.xml for delta files      
        - name: Generate the package.xml for delta files
          run: |
            sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output . --ignore-whitespace -d -i .sgdignore 
            echo "--- package.xml generated with added and modified metadata ---"
            cat package/package.xml

      # Validate Delta components to Salesforce    
        - name: Validate Delta components to Salesforce
          run: |
             sfdx force:source:deploy -p -c delta
          #sfdx force:source:deploy -x package/package.xml -l NoTestRun -u target_poc -c
       #sf project deploy validate package/package.xml -l NoTestRun -u target_poc -c
          # sfdx force:source:deploy -c -p force-app -u target_poc
            
            
