name: Salesforce Deployments

on:
  push:
    branches: main

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: install salesforce cli
          run: |
            npm install sfdx-cli --global

        - name: Authenticate with salesforce
          run: |
            echo ${{ secrets.SFDX_AUTH_URL }} > ./authfile.txt
            sfdx force:auth:sfdxurl:store -f ./authfile.txt --setalias target_poc -s

        - name: Deploy to org
          run: |
            sfdx force:source:deploy -c -p force-app -u target_poc
            sfdx force:source:deploy -p force-app -u target_poc
